"⚙️ CI関連":
  - changed-files:
      - any-glob-to-any-file:
          [".github/**/*", ".lintstagedrc", ".prettierrc.mjs", ".eslintrc.cjs"]

"📚 ドキュメント":
  - changed-files:
      - any-glob-to-any-file: ["**/*.md"]
