name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: "20.x"
  PNPM_VERSION: "9.9.0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup and install
        uses: ./.github/actions/setup-and-install

      - name: Lint
        run: pnpm run lint
        env:
          DEBUG_URL: ${{ vars.DUMMY_DEBUG_URL }}

      - name: Format check
        run: pnpm run format

      - name: Type check
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
        env:
          DEBUG_URL: ${{ vars.DUMMY_DEBUG_URL }}
